#!/bin/python3

import argparse
import json
import os
import sys

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('input')
    parser.add_argument('output')
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f'Error: Couldn\'t find file {args.input}')
        sys.exit(-1)
    with open(args.input, 'r') as f:
        raw_contents = json.load(f)
    assert 'layers' in raw_contents.keys()
    contents = []

    gids = [t['firstgid'] for t in raw_contents['tilesets']]
    def to_local_id(d):
        last_gid = gids[0]
        for gid in gids:
            if d < gid:
                break
            last_gid = gid
        return max(d - last_gid, 0)

    for layer in raw_contents['layers']:
        contents.append(f'static u16_t const TILEMAP_{layer['name']}[] = {{')
        size = 0
        if 'data' in layer:
            contents.append(', '.join((str(to_local_id(d)) for d in layer['data'])))
            size = len(layer['data'])
        contents.append('};')
        contents.append(f'static u16_t const TILEMAP_{layer['name']}_SIZE = {size};');

    with open(args.output, "w") as f:
        f.write('\n'.join(contents))

    sys.exit(0)

